# Generated by Django 4.0.5 on 2022-06-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(choices=[('', ''), ('Ona Tili', 'Ona Tili'), ('Adabiyot', 'Adabiyot'), ('Matematika', 'Matematika'), ('Ingliz Tili', 'Ingliz Tili'), ('Odobnoma', 'Odobnoma'), ('Jahon Tarix', 'Jahon Tarix'), ('O`zbekiston Tarix', 'O`zbekiston Tarix'), ('Musiqa', 'Musiqa')], max_length=33)),
                ('class_numbers', models.ManyToManyField(to='information.classnum')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='information.classnum')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='information.subjects')),
            ],
        ),
    ]
