# Generated by Django 4.0.5 on 2022-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_class_number'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnum',
            name='pupils',
            field=models.ManyToManyField(to='users.pupil'),
        ),
    ]
