# Generated by Django 4.0.5 on 2022-06-11 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_class_number'),
        ('information', '0002_classnum_pupils'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='nb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal',
            name='ratings',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
        ),
    ]
