# Generated by Django 4.0.5 on 2022-06-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_journal_nb_journal_ratings_journal_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='ratings',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
