# Generated by Django 4.0.5 on 2022-06-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_alter_journal_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classnum',
            name='pupils',
        ),
    ]
