# Generated by Django 4.0.5 on 2022-06-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_class_number'),
        ('information', '0008_remove_classnum_pupils'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='pupil',
            field=models.ManyToManyField(related_name='pupils', to='users.pupil'),
        ),
    ]
