# Generated by Django 4.0.5 on 2022-06-11 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0012_remove_journal_pupil_journal_pupil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='class_numbers',
        ),
    ]
