# Generated by Django 4.0.5 on 2022-06-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_class_number'),
        ('information', '0013_remove_subjects_class_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.teacher'),
        ),
    ]
