# Generated by Django 4.0.5 on 2022-06-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='class_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='information.classnum'),
        ),
    ]
