# Generated by Django 4.0.5 on 2022-06-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_class_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='class_number',
        ),
        migrations.AddField(
            model_name='user',
            name='is_pupil',
            field=models.BooleanField(default=False),
        ),
    ]
