# Generated by Django 4.0.5 on 2022-06-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_classnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassNumber',
        ),
    ]
